"""
lab_tests_db.py
===============

Database of common Indian laboratory tests with reference ranges.

This is a pure-data module (dicts/lists only, no functions, no imports).
It is self-contained and importable:

    from synthetic_data.lab_tests_db import (
        LAB_TESTS, LAB_PANELS, LAB_CHAINS, DOCTOR_SPECIALTIES,
    )

Conventions
-----------
- Units follow Indian diagnostic lab practice. India predominantly uses
  mg/dL (NOT mmol/L) for glucose, cholesterol, bilirubin, creatinine, urea,
  uric acid, calcium, etc. Electrolytes (Na, K, Cl) use mmol/L.
- Reference ranges are standard adult ranges commonly used in Indian labs.
- `ref_range` is a dict with `male` and `female` keys, each holding
  {"low": float, "high": float}. When the range is sex-independent, both
  entries hold the same values.
- `critical_low` / `critical_high` are floats or None (null) marking values
  outside which a result is clinically critical / life-threatening.
- `decimal_places` indicates how many decimals a numeric result typically
  carries (0, 1, or 2).
- `common_abnormal` is one of: "high", "low", "either", "none".
- For qualitative / string-value tests (urine routine, blood group, widal,
  dengue, malaria, COVID, pregnancy, stool), `ref_range` is None and
  `decimal_places` is 0. The allowed string values are listed under the
  `values` key.
"""

# ---------------------------------------------------------------------------
# 1. LAB_TESTS
#    Keyed by snake_case test name.
# ---------------------------------------------------------------------------
LAB_TESTS = {
    # ===================== Complete Blood Count (CBC) =====================
    "hemoglobin": {
        "name": "Hemoglobin",
        "short_name": "Hb",
        "category": "Complete Blood Count",
        "unit": "g/dL",
        "ref_range": {
            "male": {"low": 13.5, "high": 17.5},
            "female": {"low": 12.0, "high": 15.5},
        },
        "critical_low": 7.0,
        "critical_high": 20.0,
        "decimal_places": 1,
        "common_abnormal": "low",
    },
    "tlc": {
        "name": "Total Leucocyte Count",
        "short_name": "TLC",
        "category": "Complete Blood Count",
        "unit": "/µL",
        "ref_range": {
            "male": {"low": 4000.0, "high": 11000.0},
            "female": {"low": 4000.0, "high": 11000.0},
        },
        "critical_low": 2000.0,
        "critical_high": 30000.0,
        "decimal_places": 0,
        "common_abnormal": "either",
    },
    "neutrophils": {
        "name": "Differential Count - Neutrophils",
        "short_name": "Neutrophils",
        "category": "Complete Blood Count",
        "unit": "%",
        "ref_range": {
            "male": {"low": 40.0, "high": 75.0},
            "female": {"low": 40.0, "high": 75.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "either",
    },
    "lymphocytes": {
        "name": "Differential Count - Lymphocytes",
        "short_name": "Lymphocytes",
        "category": "Complete Blood Count",
        "unit": "%",
        "ref_range": {
            "male": {"low": 20.0, "high": 50.0},
            "female": {"low": 20.0, "high": 50.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "either",
    },
    "monocytes": {
        "name": "Differential Count - Monocytes",
        "short_name": "Monocytes",
        "category": "Complete Blood Count",
        "unit": "%",
        "ref_range": {
            "male": {"low": 2.0, "high": 10.0},
            "female": {"low": 2.0, "high": 10.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "eosinophils": {
        "name": "Differential Count - Eosinophils",
        "short_name": "Eosinophils",
        "category": "Complete Blood Count",
        "unit": "%",
        "ref_range": {
            "male": {"low": 1.0, "high": 6.0},
            "female": {"low": 1.0, "high": 6.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "basophils": {
        "name": "Differential Count - Basophils",
        "short_name": "Basophils",
        "category": "Complete Blood Count",
        "unit": "%",
        "ref_range": {
            "male": {"low": 0.0, "high": 2.0},
            "female": {"low": 0.0, "high": 2.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "rbc_count": {
        "name": "RBC Count",
        "short_name": "RBC",
        "category": "Complete Blood Count",
        "unit": "x10^6/µL",
        "ref_range": {
            "male": {"low": 4.5, "high": 6.0},
            "female": {"low": 4.0, "high": 5.5},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 2,
        "common_abnormal": "low",
    },
    "platelet_count": {
        "name": "Platelet Count",
        "short_name": "PLT",
        "category": "Complete Blood Count",
        "unit": "x10^3/µL",
        "ref_range": {
            "male": {"low": 150000.0, "high": 450000.0},
            "female": {"low": 150000.0, "high": 450000.0},
        },
        "critical_low": 50000.0,
        "critical_high": 1000000.0,
        "decimal_places": 0,
        "common_abnormal": "low",
    },
    "hematocrit": {
        "name": "PCV / Hematocrit",
        "short_name": "PCV",
        "category": "Complete Blood Count",
        "unit": "%",
        "ref_range": {
            "male": {"low": 40.0, "high": 54.0},
            "female": {"low": 36.0, "high": 48.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "low",
    },
    "mcv": {
        "name": "Mean Corpuscular Volume",
        "short_name": "MCV",
        "category": "Complete Blood Count",
        "unit": "fl",
        "ref_range": {
            "male": {"low": 80.0, "high": 100.0},
            "female": {"low": 80.0, "high": 100.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "either",
    },
    "mch": {
        "name": "Mean Corpuscular Hemoglobin",
        "short_name": "MCH",
        "category": "Complete Blood Count",
        "unit": "pg",
        "ref_range": {
            "male": {"low": 27.0, "high": 33.0},
            "female": {"low": 27.0, "high": 33.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "either",
    },
    "mchc": {
        "name": "Mean Corpuscular Hemoglobin Concentration",
        "short_name": "MCHC",
        "category": "Complete Blood Count",
        "unit": "g/dL",
        "ref_range": {
            "male": {"low": 32.0, "high": 37.0},
            "female": {"low": 32.0, "high": 37.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "either",
    },
    "rdw": {
        "name": "Red Cell Distribution Width",
        "short_name": "RDW",
        "category": "Complete Blood Count",
        "unit": "%",
        "ref_range": {
            "male": {"low": 11.5, "high": 14.5},
            "female": {"low": 11.5, "high": 14.5},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "high",
    },
    "esr": {
        "name": "Erythrocyte Sedimentation Rate",
        "short_name": "ESR",
        "category": "Complete Blood Count",
        "unit": "mm/hr",
        "ref_range": {
            "male": {"low": 0.0, "high": 15.0},
            "female": {"low": 0.0, "high": 20.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },

    # ===================== Liver Function Test (LFT) =====================
    "total_bilirubin": {
        "name": "Total Bilirubin",
        "short_name": "T. Bilirubin",
        "category": "Liver Function Test",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 0.2, "high": 1.2},
            "female": {"low": 0.2, "high": 1.2},
        },
        "critical_low": None,
        "critical_high": 20.0,
        "decimal_places": 1,
        "common_abnormal": "high",
    },
    "direct_bilirubin": {
        "name": "Direct Bilirubin",
        "short_name": "D. Bilirubin",
        "category": "Liver Function Test",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 0.0, "high": 0.4},
            "female": {"low": 0.0, "high": 0.4},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "high",
    },
    "indirect_bilirubin": {
        "name": "Indirect Bilirubin",
        "short_name": "I. Bilirubin",
        "category": "Liver Function Test",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 0.2, "high": 0.8},
            "female": {"low": 0.2, "high": 0.8},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "high",
    },
    "sgpt": {
        "name": "SGPT / ALT",
        "short_name": "SGPT",
        "category": "Liver Function Test",
        "unit": "U/L",
        "ref_range": {
            "male": {"low": 7.0, "high": 56.0},
            "female": {"low": 7.0, "high": 56.0},
        },
        "critical_low": None,
        "critical_high": 1000.0,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "sgot": {
        "name": "SGOT / AST",
        "short_name": "SGOT",
        "category": "Liver Function Test",
        "unit": "U/L",
        "ref_range": {
            "male": {"low": 10.0, "high": 40.0},
            "female": {"low": 10.0, "high": 40.0},
        },
        "critical_low": None,
        "critical_high": 500.0,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "alp": {
        "name": "Alkaline Phosphatase",
        "short_name": "ALP",
        "category": "Liver Function Test",
        "unit": "U/L",
        "ref_range": {
            "male": {"low": 44.0, "high": 147.0},
            "female": {"low": 44.0, "high": 147.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "total_protein": {
        "name": "Total Protein",
        "short_name": "T. Protein",
        "category": "Liver Function Test",
        "unit": "g/dL",
        "ref_range": {
            "male": {"low": 6.0, "high": 8.3},
            "female": {"low": 6.0, "high": 8.3},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "either",
    },
    "albumin": {
        "name": "Albumin",
        "short_name": "Albumin",
        "category": "Liver Function Test",
        "unit": "g/dL",
        "ref_range": {
            "male": {"low": 3.5, "high": 5.0},
            "female": {"low": 3.5, "high": 5.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "low",
    },
    "globulin": {
        "name": "Globulin",
        "short_name": "Globulin",
        "category": "Liver Function Test",
        "unit": "g/dL",
        "ref_range": {
            "male": {"low": 2.0, "high": 3.5},
            "female": {"low": 2.0, "high": 3.5},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "either",
    },
    "ag_ratio": {
        "name": "A/G Ratio",
        "short_name": "A/G",
        "category": "Liver Function Test",
        "unit": "",
        "ref_range": {
            "male": {"low": 1.0, "high": 2.0},
            "female": {"low": 1.0, "high": 2.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 2,
        "common_abnormal": "low",
    },
    "ggt": {
        "name": "Gamma Glutamyl Transferase",
        "short_name": "GGT",
        "category": "Liver Function Test",
        "unit": "U/L",
        "ref_range": {
            "male": {"low": 9.0, "high": 48.0},
            "female": {"low": 9.0, "high": 48.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },

    # ===================== Kidney Function Test (KFT) =====================
    "urea": {
        "name": "Urea",
        "short_name": "Urea",
        "category": "Kidney Function Test",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 15.0, "high": 40.0},
            "female": {"low": 15.0, "high": 40.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "creatinine": {
        "name": "Creatinine",
        "short_name": "Creatinine",
        "category": "Kidney Function Test",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 0.7, "high": 1.3},
            "female": {"low": 0.6, "high": 1.1},
        },
        "critical_low": None,
        "critical_high": 10.0,
        "decimal_places": 1,
        "common_abnormal": "high",
    },
    "uric_acid": {
        "name": "Uric Acid",
        "short_name": "Uric Acid",
        "category": "Kidney Function Test",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 3.4, "high": 7.0},
            "female": {"low": 2.4, "high": 6.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "high",
    },
    "sodium": {
        "name": "Sodium",
        "short_name": "Na",
        "category": "Kidney Function Test",
        "unit": "mmol/L",
        "ref_range": {
            "male": {"low": 135.0, "high": 145.0},
            "female": {"low": 135.0, "high": 145.0},
        },
        "critical_low": 120.0,
        "critical_high": 160.0,
        "decimal_places": 0,
        "common_abnormal": "either",
    },
    "potassium": {
        "name": "Potassium",
        "short_name": "K",
        "category": "Kidney Function Test",
        "unit": "mmol/L",
        "ref_range": {
            "male": {"low": 3.5, "high": 5.1},
            "female": {"low": 3.5, "high": 5.1},
        },
        "critical_low": 2.5,
        "critical_high": 6.5,
        "decimal_places": 1,
        "common_abnormal": "either",
    },
    "chloride": {
        "name": "Chloride",
        "short_name": "Cl",
        "category": "Kidney Function Test",
        "unit": "mmol/L",
        "ref_range": {
            "male": {"low": 98.0, "high": 107.0},
            "female": {"low": 98.0, "high": 107.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "either",
    },
    "bun": {
        "name": "Blood Urea Nitrogen",
        "short_name": "BUN",
        "category": "Kidney Function Test",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 7.0, "high": 20.0},
            "female": {"low": 7.0, "high": 20.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "egfr": {
        "name": "Estimated Glomerular Filtration Rate",
        "short_name": "eGFR",
        "category": "Kidney Function Test",
        "unit": "mL/min/1.73m2",
        "ref_range": {
            "male": {"low": 90.0, "high": 120.0},
            "female": {"low": 90.0, "high": 120.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "low",
    },

    # ===================== Diabetes =====================
    "fbs": {
        "name": "Fasting Blood Sugar",
        "short_name": "FBS",
        "category": "Diabetes",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 70.0, "high": 100.0},
            "female": {"low": 70.0, "high": 100.0},
        },
        "critical_low": 40.0,
        "critical_high": 400.0,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "ppbs": {
        "name": "Post Prandial Blood Sugar",
        "short_name": "PPBS",
        "category": "Diabetes",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 70.0, "high": 140.0},
            "female": {"low": 70.0, "high": 140.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "rbs": {
        "name": "Random Blood Sugar",
        "short_name": "RBS",
        "category": "Diabetes",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 70.0, "high": 140.0},
            "female": {"low": 70.0, "high": 140.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "hba1c": {
        "name": "Glycosylated Hemoglobin",
        "short_name": "HbA1c",
        "category": "Diabetes",
        "unit": "%",
        "ref_range": {
            "male": {"low": 4.0, "high": 5.6},
            "female": {"low": 4.0, "high": 5.6},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "high",
    },
    "fructosamine": {
        "name": "Fructosamine",
        "short_name": "Fructosamine",
        "category": "Diabetes",
        "unit": "µmol/L",
        "ref_range": {
            "male": {"low": 200.0, "high": 285.0},
            "female": {"low": 200.0, "high": 285.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },

    # ===================== Lipid Profile =====================
    "total_cholesterol": {
        "name": "Total Cholesterol",
        "short_name": "T. Cholesterol",
        "category": "Lipid Profile",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 0.0, "high": 200.0},
            "female": {"low": 0.0, "high": 200.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "triglycerides": {
        "name": "Triglycerides",
        "short_name": "TG",
        "category": "Lipid Profile",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 0.0, "high": 150.0},
            "female": {"low": 0.0, "high": 150.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "hdl": {
        "name": "HDL Cholesterol",
        "short_name": "HDL",
        "category": "Lipid Profile",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 40.0, "high": 60.0},
            "female": {"low": 50.0, "high": 60.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "low",
    },
    "ldl": {
        "name": "LDL Cholesterol",
        "short_name": "LDL",
        "category": "Lipid Profile",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 0.0, "high": 100.0},
            "female": {"low": 0.0, "high": 100.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "vldl": {
        "name": "VLDL Cholesterol",
        "short_name": "VLDL",
        "category": "Lipid Profile",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 5.0, "high": 40.0},
            "female": {"low": 5.0, "high": 40.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "tc_hdl_ratio": {
        "name": "Total Cholesterol/HDL Ratio",
        "short_name": "TC/HDL",
        "category": "Lipid Profile",
        "unit": "",
        "ref_range": {
            "male": {"low": 0.0, "high": 3.5},
            "female": {"low": 0.0, "high": 3.5},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 2,
        "common_abnormal": "high",
    },
    "ldl_hdl_ratio": {
        "name": "LDL/HDL Ratio",
        "short_name": "LDL/HDL",
        "category": "Lipid Profile",
        "unit": "",
        "ref_range": {
            "male": {"low": 0.0, "high": 3.0},
            "female": {"low": 0.0, "high": 3.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 2,
        "common_abnormal": "high",
    },

    # ===================== Thyroid Profile =====================
    "t3": {
        "name": "Triiodothyronine",
        "short_name": "T3",
        "category": "Thyroid Profile",
        "unit": "ng/dL",
        "ref_range": {
            "male": {"low": 80.0, "high": 200.0},
            "female": {"low": 80.0, "high": 200.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "either",
    },
    "t4": {
        "name": "Thyroxine",
        "short_name": "T4",
        "category": "Thyroid Profile",
        "unit": "µg/dL",
        "ref_range": {
            "male": {"low": 5.0, "high": 12.0},
            "female": {"low": 5.0, "high": 12.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "either",
    },
    "tsh": {
        "name": "Thyroid Stimulating Hormone",
        "short_name": "TSH",
        "category": "Thyroid Profile",
        "unit": "µIU/mL",
        "ref_range": {
            "male": {"low": 0.4, "high": 4.0},
            "female": {"low": 0.4, "high": 4.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 2,
        "common_abnormal": "either",
    },

    # ===================== Vitamins & Minerals =====================
    "vitamin_d": {
        "name": "Vitamin D (25-OH)",
        "short_name": "Vit D",
        "category": "Vitamins",
        "unit": "ng/mL",
        "ref_range": {
            "male": {"low": 30.0, "high": 100.0},
            "female": {"low": 30.0, "high": 100.0},
        },
        "critical_low": 10.0,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "low",
    },
    "vitamin_b12": {
        "name": "Vitamin B12",
        "short_name": "Vit B12",
        "category": "Vitamins",
        "unit": "pg/mL",
        "ref_range": {
            "male": {"low": 200.0, "high": 900.0},
            "female": {"low": 200.0, "high": 900.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "low",
    },
    "folate": {
        "name": "Folate / Folic Acid",
        "short_name": "Folate",
        "category": "Vitamins",
        "unit": "ng/mL",
        "ref_range": {
            "male": {"low": 3.0, "high": 17.0},
            "female": {"low": 3.0, "high": 17.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "low",
    },
    "serum_calcium": {
        "name": "Serum Calcium",
        "short_name": "Ca",
        "category": "Vitamins",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 8.6, "high": 10.3},
            "female": {"low": 8.6, "high": 10.3},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "either",
    },
    "serum_phosphorus": {
        "name": "Serum Phosphorus",
        "short_name": "P",
        "category": "Vitamins",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 2.5, "high": 4.5},
            "female": {"low": 2.5, "high": 4.5},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "either",
    },
    "serum_magnesium": {
        "name": "Serum Magnesium",
        "short_name": "Mg",
        "category": "Vitamins",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 1.7, "high": 2.2},
            "female": {"low": 1.7, "high": 2.2},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "either",
    },
    "serum_iron": {
        "name": "Serum Iron",
        "short_name": "Fe",
        "category": "Vitamins",
        "unit": "µg/dL",
        "ref_range": {
            "male": {"low": 65.0, "high": 176.0},
            "female": {"low": 26.0, "high": 170.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "low",
    },
    "tibc": {
        "name": "Total Iron Binding Capacity",
        "short_name": "TIBC",
        "category": "Vitamins",
        "unit": "µg/dL",
        "ref_range": {
            "male": {"low": 240.0, "high": 450.0},
            "female": {"low": 240.0, "high": 450.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "either",
    },
    "ferritin": {
        "name": "Ferritin",
        "short_name": "Ferritin",
        "category": "Vitamins",
        "unit": "ng/mL",
        "ref_range": {
            "male": {"low": 24.0, "high": 336.0},
            "female": {"low": 11.0, "high": 307.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "low",
    },
    "serum_zinc": {
        "name": "Serum Zinc",
        "short_name": "Zn",
        "category": "Vitamins",
        "unit": "µg/dL",
        "ref_range": {
            "male": {"low": 70.0, "high": 120.0},
            "female": {"low": 70.0, "high": 120.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "low",
    },

    # ===================== Cardiac / Cardiac Markers =====================
    "troponin_i": {
        "name": "Troponin I",
        "short_name": "Trop I",
        "category": "Cardiac",
        "unit": "ng/mL",
        "ref_range": {
            "male": {"low": 0.0, "high": 0.04},
            "female": {"low": 0.0, "high": 0.04},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 2,
        "common_abnormal": "high",
    },
    "ck_mb": {
        "name": "Creatine Kinase-MB",
        "short_name": "CK-MB",
        "category": "Cardiac",
        "unit": "U/L",
        "ref_range": {
            "male": {"low": 0.0, "high": 25.0},
            "female": {"low": 0.0, "high": 25.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "cpk": {
        "name": "Creatine Phosphokinase",
        "short_name": "CPK",
        "category": "Cardiac",
        "unit": "U/L",
        "ref_range": {
            "male": {"low": 30.0, "high": 200.0},
            "female": {"low": 30.0, "high": 200.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "ldh": {
        "name": "Lactate Dehydrogenase",
        "short_name": "LDH",
        "category": "Cardiac",
        "unit": "U/L",
        "ref_range": {
            "male": {"low": 140.0, "high": 280.0},
            "female": {"low": 140.0, "high": 280.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },
    "nt_probnp": {
        "name": "NT-proBNP",
        "short_name": "NT-proBNP",
        "category": "Cardiac",
        "unit": "pg/mL",
        "ref_range": {
            "male": {"low": 0.0, "high": 125.0},
            "female": {"low": 0.0, "high": 125.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
    },

    # ===================== Coagulation =====================
    "pt": {
        "name": "Prothrombin Time",
        "short_name": "PT",
        "category": "Coagulation",
        "unit": "seconds",
        "ref_range": {
            "male": {"low": 11.0, "high": 14.0},
            "female": {"low": 11.0, "high": 14.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "high",
    },
    "inr": {
        "name": "International Normalized Ratio",
        "short_name": "INR",
        "category": "Coagulation",
        "unit": "",
        "ref_range": {
            "male": {"low": 0.8, "high": 1.2},
            "female": {"low": 0.8, "high": 1.2},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "high",
    },
    "aptt": {
        "name": "Activated Partial Thromboplastin Time",
        "short_name": "APTT",
        "category": "Coagulation",
        "unit": "seconds",
        "ref_range": {
            "male": {"low": 25.0, "high": 35.0},
            "female": {"low": 25.0, "high": 35.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "either",
    },
    "d_dimer": {
        "name": "D-Dimer",
        "short_name": "D-Dimer",
        "category": "Coagulation",
        "unit": "µg/mL",
        "ref_range": {
            "male": {"low": 0.0, "high": 0.5},
            "female": {"low": 0.0, "high": 0.5},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 2,
        "common_abnormal": "high",
    },
    "fibrinogen": {
        "name": "Fibrinogen",
        "short_name": "Fibrinogen",
        "category": "Coagulation",
        "unit": "mg/dL",
        "ref_range": {
            "male": {"low": 200.0, "high": 400.0},
            "female": {"low": 200.0, "high": 400.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "either",
    },

    # ===================== Inflammatory Markers =====================
    "crp": {
        "name": "C-Reactive Protein",
        "short_name": "CRP",
        "category": "Inflammatory Markers",
        "unit": "mg/L",
        "ref_range": {
            "male": {"low": 0.0, "high": 5.0},
            "female": {"low": 0.0, "high": 5.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "high",
    },
    "procalcitonin": {
        "name": "Procalcitonin",
        "short_name": "PCT",
        "category": "Inflammatory Markers",
        "unit": "ng/mL",
        "ref_range": {
            "male": {"low": 0.0, "high": 0.1},
            "female": {"low": 0.0, "high": 0.1},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 2,
        "common_abnormal": "high",
    },

    # ===================== Urine Routine =====================
    "urine_color": {
        "name": "Urine Color",
        "short_name": "Color",
        "category": "Urine",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "none",
        "values": ["Yellow", "Pale Yellow", "Dark Yellow", "Straw"],
    },
    "urine_appearance": {
        "name": "Urine Appearance",
        "short_name": "Appearance",
        "category": "Urine",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "none",
        "values": ["Clear", "Slightly Hazy", "Hazy", "Cloudy"],
    },
    "urine_ph": {
        "name": "Urine pH",
        "short_name": "pH",
        "category": "Urine",
        "unit": "",
        "ref_range": {
            "male": {"low": 5.0, "high": 8.0},
            "female": {"low": 5.0, "high": 8.0},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 1,
        "common_abnormal": "either",
    },
    "urine_specific_gravity": {
        "name": "Urine Specific Gravity",
        "short_name": "Sp. Gravity",
        "category": "Urine",
        "unit": "",
        "ref_range": {
            "male": {"low": 1.005, "high": 1.030},
            "female": {"low": 1.005, "high": 1.030},
        },
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 3,
        "common_abnormal": "either",
    },
    "urine_protein": {
        "name": "Urine Protein",
        "short_name": "Protein",
        "category": "Urine",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
        "values": ["Nil", "Trace", "1+", "2+", "3+"],
    },
    "urine_sugar": {
        "name": "Urine Sugar",
        "short_name": "Sugar",
        "category": "Urine",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
        "values": ["Nil", "Trace", "1+", "2+", "3+"],
    },
    "urine_pus_cells": {
        "name": "Urine Pus Cells",
        "short_name": "Pus Cells",
        "category": "Urine",
        "unit": "/hpf",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
        "values": ["0-2", "0-5", "5-10", "10-15", "15-20", ">20"],
    },
    "urine_rbc": {
        "name": "Urine RBC",
        "short_name": "RBC",
        "category": "Urine",
        "unit": "/hpf",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
        "values": ["0-2", "2-5", "5-10", "10-15", ">15"],
    },
    "urine_epithelial_cells": {
        "name": "Urine Epithelial Cells",
        "short_name": "Epithelial",
        "category": "Urine",
        "unit": "/hpf",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
        "values": ["0-2", "0-5", "5-10", "10-15", ">15"],
    },

    # ===================== Stool =====================
    "stool_occult_blood": {
        "name": "Stool Occult Blood",
        "short_name": "OB",
        "category": "Stool",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
        "values": ["Negative", "Positive"],
    },
    "stool_consistency": {
        "name": "Stool Consistency",
        "short_name": "Consistency",
        "category": "Stool",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "none",
        "values": ["Solid", "Semi-solid", "Liquid"],
    },
    "stool_mucus": {
        "name": "Stool Mucus",
        "short_name": "Mucus",
        "category": "Stool",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
        "values": ["Absent", "Present"],
    },

    # ===================== Miscellaneous =====================
    "blood_group": {
        "name": "Blood Group",
        "short_name": "Blood Group",
        "category": "Miscellaneous",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "none",
        "values": ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
    },
    "widal_o": {
        "name": "Widal (O Antigen)",
        "short_name": "Widal O",
        "category": "Miscellaneous",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
        "values": ["Negative", "1:80", "1:160", "1:320"],
    },
    "widal_h": {
        "name": "Widal (H Antigen)",
        "short_name": "Widal H",
        "category": "Miscellaneous",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
        "values": ["Negative", "1:80", "1:160", "1:320"],
    },
    "dengue_ns1": {
        "name": "Dengue NS1",
        "short_name": "NS1",
        "category": "Miscellaneous",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
        "values": ["Negative", "Positive"],
    },
    "malaria_antigen": {
        "name": "Malaria Antigen",
        "short_name": "Malaria",
        "category": "Miscellaneous",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
        "values": ["Negative", "P. falciparum", "P. vivax"],
    },
    "covid_rt_pcr": {
        "name": "COVID-19 RT-PCR",
        "short_name": "COVID-19",
        "category": "Miscellaneous",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
        "values": ["Negative", "Positive"],
    },
    "pregnancy_test": {
        "name": "Pregnancy Test (Urine)",
        "short_name": "UPT",
        "category": "Miscellaneous",
        "unit": "",
        "ref_range": None,
        "critical_low": None,
        "critical_high": None,
        "decimal_places": 0,
        "common_abnormal": "high",
        "values": ["Negative", "Positive"],
    },
}

# ---------------------------------------------------------------------------
# 2. LAB_PANELS
#    Keyed by panel name. Each value is a list of test keys from LAB_TESTS.
# ---------------------------------------------------------------------------
LAB_PANELS = {
    "Complete Blood Count": [
        "hemoglobin",
        "tlc",
        "neutrophils",
        "lymphocytes",
        "monocytes",
        "eosinophils",
        "basophils",
        "rbc_count",
        "platelet_count",
        "hematocrit",
        "mcv",
        "mch",
        "mchc",
        "rdw",
        "esr",
    ],
    "Liver Function Test": [
        "total_bilirubin",
        "direct_bilirubin",
        "indirect_bilirubin",
        "sgpt",
        "sgot",
        "alp",
        "total_protein",
        "albumin",
        "globulin",
        "ag_ratio",
        "ggt",
    ],
    "Kidney Function Test": [
        "urea",
        "creatinine",
        "uric_acid",
        "sodium",
        "potassium",
        "chloride",
        "bun",
        "egfr",
    ],
    "Lipid Profile": [
        "total_cholesterol",
        "triglycerides",
        "hdl",
        "ldl",
        "vldl",
        "tc_hdl_ratio",
        "ldl_hdl_ratio",
    ],
    "Thyroid Profile": [
        "t3",
        "t4",
        "tsh",
    ],
    "Diabetes Panel": [
        "fbs",
        "ppbs",
        "hba1c",
    ],
    "Vitamin Profile": [
        "vitamin_d",
        "vitamin_b12",
        "folate",
    ],
    "Iron Studies": [
        "serum_iron",
        "tibc",
        "ferritin",
    ],
    "Cardiac Markers": [
        "troponin_i",
        "ck_mb",
        "cpk",
    ],
    "Coagulation Profile": [
        "pt",
        "inr",
        "aptt",
        "d_dimer",
    ],
    "Urine Routine": [
        "urine_color",
        "urine_appearance",
        "urine_ph",
        "urine_specific_gravity",
        "urine_protein",
        "urine_sugar",
        "urine_pus_cells",
        "urine_rbc",
        "urine_epithelial_cells",
    ],
    "Fever Profile": [
        "hemoglobin",
        "tlc",
        "neutrophils",
        "lymphocytes",
        "platelet_count",
        "esr",
        "crp",
        "widal_o",
        "widal_h",
        "dengue_ns1",
        "malaria_antigen",
    ],
    "Electrolytes": [
        "sodium",
        "potassium",
        "chloride",
    ],
    "Inflammatory Markers": [
        "crp",
        "procalcitonin",
    ],
    "Stool Routine": [
        "stool_occult_blood",
        "stool_consistency",
        "stool_mucus",
    ],
}

# ---------------------------------------------------------------------------
# 3. LAB_CHAINS
#    Common Indian diagnostic lab chains (real + realistic fictional names).
# ---------------------------------------------------------------------------
LAB_CHAINS = [
    {"name": "Dr. Lal PathLabs", "abbr": "LPL", "nabl": True},
    {"name": "Thyrocare", "abbr": "THY", "nabl": True},
    {"name": "Metropolis Healthcare", "abbr": "MET", "nabl": True},
    {"name": "SRL Diagnostics", "abbr": "SRL", "nabl": True},
    {"name": "Apollo Diagnostics", "abbr": "APL", "nabl": True},
    {"name": "Redcliffe Labs", "abbr": "RCL", "nabl": True},
    {"name": "Healthians", "abbr": "HLT", "nabl": True},
    {"name": "PharmEasy Labs", "abbr": "PEL", "nabl": True},
    {"name": "Suraksha Diagnostics", "abbr": "SRK", "nabl": True},
    {"name": "Vijaya Diagnostic Centre", "abbr": "VDC", "nabl": True},
    {"name": "Agilus Diagnostics", "abbr": "AGL", "nabl": True},
    {"name": "Narayana Health Diagnostics", "abbr": "NHD", "nabl": True},
    {"name": "Aarogyam Diagnostics", "abbr": "AAR", "nabl": True},
    {"name": "Indus Health Plus", "abbr": "IHP", "nabl": True},
    {"name": "Anand Lab Centre", "abbr": "ALC", "nabl": False},
    {"name": "Bharat Path Labs", "abbr": "BPL", "nabl": True},
    {"name": "Carewell Diagnostics", "abbr": "CWD", "nabl": False},
    {"name": "Meditest Labs", "abbr": "MDT", "nabl": True},
]

# ---------------------------------------------------------------------------
# 4. DOCTOR_SPECIALTIES
#    Indian medical specialties with typical qualifications.
# ---------------------------------------------------------------------------
DOCTOR_SPECIALTIES = [
    {"specialty": "General Physician", "qualifications": "MBBS, MD (Medicine)", "prefix": "Dr."},
    {"specialty": "Pediatrician", "qualifications": "MBBS, MD (Pediatrics)", "prefix": "Dr."},
    {"specialty": "Cardiologist", "qualifications": "MBBS, MD, DM (Cardiology)", "prefix": "Dr."},
    {"specialty": "Diabetologist", "qualifications": "MBBS, MD, Fellowship (Diabetes)", "prefix": "Dr."},
    {"specialty": "Orthopedic Surgeon", "qualifications": "MBBS, MS (Ortho)", "prefix": "Dr."},
    {"specialty": "Gynecologist", "qualifications": "MBBS, MS (OBG)", "prefix": "Dr."},
    {"specialty": "Dermatologist", "qualifications": "MBBS, MD (Dermatology)", "prefix": "Dr."},
    {"specialty": "ENT Specialist", "qualifications": "MBBS, MS (ENT)", "prefix": "Dr."},
    {"specialty": "Ophthalmologist", "qualifications": "MBBS, MS (Ophthal)", "prefix": "Dr."},
    {"specialty": "General Surgeon", "qualifications": "MBBS, MS (Surgery)", "prefix": "Dr."},
    {"specialty": "Physician", "qualifications": "MBBS", "prefix": "Dr."},
    {"specialty": "Neurologist", "qualifications": "MBBS, MD, DM (Neurology)", "prefix": "Dr."},
    {"specialty": "Neurosurgeon", "qualifications": "MBBS, MCh (Neurosurgery)", "prefix": "Dr."},
    {"specialty": "Nephrologist", "qualifications": "MBBS, MD, DM (Nephrology)", "prefix": "Dr."},
    {"specialty": "Gastroenterologist", "qualifications": "MBBS, MD, DM (Gastroenterology)", "prefix": "Dr."},
    {"specialty": "Endocrinologist", "qualifications": "MBBS, MD, DM (Endocrinology)", "prefix": "Dr."},
    {"specialty": "Pulmonologist", "qualifications": "MBBS, MD, DM (Pulmonology)", "prefix": "Dr."},
    {"specialty": "Oncologist", "qualifications": "MBBS, MD, DM (Oncology)", "prefix": "Dr."},
    {"specialty": "Urologist", "qualifications": "MBBS, MS, MCh (Urology)", "prefix": "Dr."},
    {"specialty": "Psychiatrist", "qualifications": "MBBS, MD (Psychiatry)", "prefix": "Dr."},
    {"specialty": "General Medicine", "qualifications": "MBBS, MD (Medicine)", "prefix": "Dr."},
    {"specialty": "Pathologist", "qualifications": "MBBS, MD (Pathology)", "prefix": "Dr."},
    {"specialty": "Radiologist", "qualifications": "MBBS, MD (Radiology)", "prefix": "Dr."},
    {"specialty": "Dentist", "qualifications": "BDS", "prefix": "Dr."},
    {"specialty": "Homeopath", "qualifications": "BHMS", "prefix": "Dr."},
    {"specialty": "Ayurvedic Physician", "qualifications": "BAMS", "prefix": "Dr."},
]